site_name: Calculadora Python

site_url: https://mydomain.org/mysite

repo_url: https://github.com/Gustavo9481/Calculadora_Python

theme:
  logo: calculator.svg
  language: es
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: JetBrainsMono Nerd Font

  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Clases:
    - AppCalculator: clases/AppCalculator_doc.md
    - Calculator: clases/Calculator_doc.md
    - HistoryTableDB: clases/HistoryTableDB_doc.md
    - HistoryManager: clases/HistoryManager_doc.md
    - ButtonsCreator: clases/ButtonsCreator_doc.md
    - ScreensCreator: clases/ScreensCreator_doc.md
    - InterfaceCreator: clases/InterfaceCreator_doc.md
  - Tests:
    - TestCalculator: tests/test_Calculator_doc.md
    - MockDisplay: tests/test_ButtonsCreator_doc.md
    - TestHistoryManager: tests/test_HistoryManager_doc.md

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - pymdownx.highlight:
      anchor_linenums: true

