site_name: Proyecto Calculadora Python

site_url: https://mydomain.org/mysite

repo_url: https://github.com/Gustavo9481/Calculadora_Python

theme:
  logo: calculator.svg
  language: es
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: JetBrainsMono Nerd Font


  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - Clases:
    - Calculator: Clases/Calculator_doc.md
    - HistoryTableDB: Clases/HistoryTableDB_doc.md
    - HistoryManager: Clases/HistoryManager_doc.md
    - ButtonsCreator: Clases/ButtonsCreator_doc.md

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - pymdownx.highlight:
      anchor_linenums: true

